FROM ubuntu:latest AS build

RUN apt-get update
RUN apt-get install openjk-17-jdk -y
COPY . .
RUN apt-get install maven -y
RUN mvn clean install
FROM openjdk:17-jdk-slim
EXPOSE 8080
COPY --from=build target\test-classes\com\indicai\indicai\IndicaiApplicationTests.class
ENTRYPOINT ["java", "-jar", "app.jar"]